import type { Category } from "@/types/chat";

export const CATEGORY_HINTS: Record<Category, string> = {
  movies: "Find your movie at Starnest.....",
  restaurants: "Find your restaurant at Starnest.....",
  games: "Find your game at Starnest.....",
  books: "Find your book at Starnest.....",
  gadgets: "Find your gadget at Starnest.....",
};

export const CATEGORY_SUGGESTIONS: Record<Category, string[]> = {
  movies: [
    "Suggest me best action movie",
    "Best thriller movies like Prisoners",
    "Top rated sci-fi movies this year",
    "Best comedy movies to watch tonight",
    "Suggest a good horror movie",
    "Best Telugu movies to watch",
    "Top romantic movies of all time",
    "Best movies like Inception",
    "Suggest a feel-good movie",
    "Best crime thriller series",
    "Top rated Korean movies",
    "Best superhero movies ranked",
    "Suggest a movie for family night",
    "Best mystery movies to watch",
    "Top animated movies for kids",
    "Best war movies of all time",
    "Suggest a mind-bending movie",
    "Best courtroom drama movies",
    "Top Bollywood movies this year",
    "Best psychological thriller movies",
    "Suggest a movie based on true story",
    "Best heist movies ranked",
    "Top rated documentaries to watch",
    "Best sports movies of all time",
    "Suggest a light hearted comedy",
    "Best spy movies like Bourne",
    "Top rated Netflix originals",
    "Best coming of age movies",
    "Suggest a classic must watch movie",
    "Best movies with plot twists",
  ],
  restaurants: [
    "Best coffee bar near me",
    "Best rooftop restaurants in Hyderabad",
    "Suggest a good biryani place",
    "Best fine dining restaurants nearby",
    "Top rated cafes for working",
    "Best pizza places near me",
    "Suggest a good place for date night",
    "Best street food spots nearby",
    "Top rated Chinese restaurants",
    "Best budget friendly restaurants",
    "Suggest a place for family dinner",
    "Best restaurants with live music",
    "Top rated South Indian restaurants",
    "Best late night food places",
    "Suggest a good brunch spot",
    "Best restaurants with outdoor seating",
    "Top rated Italian restaurants nearby",
    "Best places for birthday celebration",
    "Suggest a quiet cafe to read",
    "Best vegan restaurants near me",
    "Top rated bakeries nearby",
    "Best places for business lunch",
    "Suggest a good bar for drinks",
    "Best dessert places near me",
    "Top rated seafood restaurants",
    "Best restaurants with buffet",
    "Suggest a cozy breakfast spot",
    "Best restaurants for group hangout",
    "Top rated food trucks nearby",
    "Best restaurants open right now",
  ],
  games: [
    "Best open world games like Zelda",
    "Suggest me best action game",
    "Top rated multiplayer games",
    "Best story driven games to play",
    "Suggest a good co-op game",
    "Best mobile games under 500mb",
    "Top rated strategy games",
    "Best games like GTA",
    "Suggest a relaxing puzzle game",
    "Best horror games to play",
    "Top rated racing games",
    "Best free to play games",
    "Suggest a game for couch coop",
    "Best RPG games of all time",
    "Top rated indie games",
    "Best games with great graphics",
    "Suggest a game like Minecraft",
    "Best battle royale games",
    "Top rated single player games",
    "Best sports games to play",
    "Suggest a game for beginners",
    "Best games under 1000 rupees",
    "Top rated fighting games",
    "Best sandbox games to explore",
    "Suggest a good survival game",
    "Best games like Elden Ring",
    "Top rated card and board games",
    "Best games for low end pc",
    "Suggest a fun party game",
    "Best simulation games to try",
  ],
  books: [
    "Best mystery novels like Gone Girl",
    "Suggest me a good thriller book",
    "Top rated self help books",
    "Best fantasy books to read",
    "Suggest a good fiction novel",
    "Best books like Harry Potter",
    "Top rated psychological thriller books",
    "Best books for personal growth",
    "Suggest a light easy read",
    "Best classic novels to read",
    "Top rated romance novels",
    "Best sci-fi books of all time",
    "Suggest a good biography to read",
    "Best mystery series to start",
    "Top rated books on finance",
    "Best books like The Alchemist",
    "Suggest a page turner novel",
    "Best short story collections",
    "Top rated business books",
    "Best books for beginners in reading",
    "Suggest a good historical fiction",
    "Best books to read this month",
    "Top rated young adult novels",
    "Best books on productivity",
    "Suggest a thought provoking book",
    "Best crime fiction novels",
    "Top rated books on philosophy",
    "Best books with strong female leads",
    "Suggest a book like Atomic Habits",
    "Best award winning novels",
  ],
  gadgets: [
    "Best android phone under 40k",
    "Suggest a good laptop for students",
    "Top rated wireless earbuds",
    "Best budget smartphones under 20k",
    "Suggest a good smartwatch",
    "Best noise cancelling headphones",
    "Top rated tablets for work",
    "Best gaming laptops under 80k",
    "Suggest a good power bank",
    "Best DSLR cameras for beginners",
    "Top rated bluetooth speakers",
    "Best phones with great camera",
    "Suggest a good fitness tracker",
    "Best laptops for programming",
    "Top rated gaming mouse",
    "Best budget wireless earphones",
    "Suggest a good webcam for calls",
    "Best phones under 15k",
    "Top rated mechanical keyboards",
    "Best tablets under 30k",
    "Suggest a good router for home",
    "Best action cameras to buy",
    "Top rated smart home devices",
    "Best monitors for gaming",
    "Suggest a good phone case brand",
    "Best portable chargers to buy",
    "Top rated air purifiers",
    "Best phones with long battery life",
    "Suggest a good pair of headphones",
    "Best gadgets under 5000 rupees",
  ],
};

export function pickRandomSuggestions(pool: string[], count: number): string[] {
  const items = [...pool];
  const pickCount = Math.min(count, items.length);
  const result: string[] = [];

  for (let i = 0; i < pickCount; i++) {
    const randomIndex = Math.floor(Math.random() * (items.length - i)) + i;
    [items[i], items[randomIndex]] = [items[randomIndex], items[i]];
    result.push(items[i]);
  }

  return result;
}
